# Generated by Django 3.0.3 on 2020-03-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('width', models.IntegerField(default=3)),
                ('height', models.IntegerField(default=3)),
                ('start_room', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('n_to', models.IntegerField(default=None, null=True)),
                ('s_to', models.IntegerField(default=None, null=True)),
                ('e_to', models.IntegerField(default=None, null=True)),
                ('w_to', models.IntegerField(default=None, null=True)),
                ('col', models.IntegerField(default=0, null=True)),
                ('row', models.IntegerField(default=0, null=True)),
                ('tile_num', models.IntegerField(default=0, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.World')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('currentRoom', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.Room')),
                ('currentWorld', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.World')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
