# Generated by Django 3.0.3 on 2020-03-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='World',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentColumn',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentRoom',
        ),
        migrations.RemoveField(
            model_name='player',
            name='currentRow',
        ),
    ]
