# Generated by Django 3.0.3 on 2020-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200304_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentRoom',
            field=models.IntegerField(default=0),
        ),
    ]
