# Generated by Django 3.0.3 on 2020-03-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_player_currentroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=3)),
                ('height', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='tile_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='world',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='col',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
