# Generated by Django 3.0.3 on 2020-03-05 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200305_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
