# Generated by Django 3.0.3 on 2020-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_world_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='world',
            field=models.UUIDField(),
        ),
    ]
