# Generated by Django 3.0.3 on 2020-03-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_player_currentworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentWorld',
            field=models.UUIDField(default=0),
        ),
    ]
