# Generated by Django 3.0.3 on 2020-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_auto_20200305_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentWorld',
            field=models.UUIDField(null=True),
        ),
    ]
