# Generated by Django 3.0.3 on 2020-03-06 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_auto_20200305_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='start_room',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.Room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentWorld',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.World'),
        ),
        migrations.AlterField(
            model_name='room',
            name='col',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='row',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tile_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.World'),
        ),
    ]
